function Figura2(P,X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 31-Mar-2019 19:34:23

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(2,1,1,'Parent',figure1);
hold(subplot1,'on');

% Create plot
plot(P,X1,'Parent',subplot1,'LineWidth',2,'Color',[1 0 0]);

% Create title
title('espectro de magnitud');

% Set the remaining axes properties
set(subplot1,'Color',[1 0.968627452850342 0.921568632125854],'FontName',...
    'Century Gothic','FontWeight','bold','XAxisLocation','origin','XGrid','on',...
    'YAxisLocation','origin','YGrid','on');
% Create subplot
subplot2 = subplot(2,1,2,'Parent',figure1);
hold(subplot2,'on');

% Create plot
plot(P,Y1,'Parent',subplot2,'LineWidth',2,'Color',[1 0 0]);

% Create title
title('espectro de fase');

% Set the remaining axes properties
set(subplot2,'Color',[1 0.968627452850342 0.921568632125854],'FontName',...
    'Century Gothic','FontWeight','bold','XAxisLocation','origin','XGrid','on',...
    'YAxisLocation','origin','YGrid','on');
