function Figura(X1, Y1, titulo)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 31-Mar-2019 17:32:41

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.0453879941434846 0.11 0.920937042459737 0.790702356549946]);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'ZDataSource','','DisplayName','f(x)','LineWidth',2,...
    'Color',[1 0 0]);

% Create title
title({titulo,''});

% Set the remaining axes properties
set(axes1,'Color',[0.960784316062927 0.921568632125854 0.921568632125854],...
    'FontName','Century Gothic','FontWeight','bold','XAxisLocation','origin',...
    'XGrid','on','YAxisLocation','origin','YGrid','on');
